### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by francescor** [L7R7/gitlab-ci-build-statuses#185]
several my users have problems with colors (colorblindness)
custom colors woud be appreciated (or just a different background pattern, so that even colorblind will clearly see difference... ... or maybe just make one color very dark and another very light :)

**Comment by L7R7** [comment]
Hi @francescor thank you very much for reporting this! I'm interested in improving accessibility for the tool, so I appreciate your feedback. Let's discuss how we can make this work.
From the top of my head, I see two main options:

1. Make all colors configurable at application startup via environment variables. The tool uses six different colors, all of them should be configurable. The colors that are used currently could be the default.
2. Introduction of a "colorblind mode", which swaps the color palette to something else that works for colorblind people, using different colors and/or background patterns like you suggested. The user could switch between the two modes similar to how they can switch between plain view and grouped view

The first option is definitely more flexible, but requires some effort on the user side when deploying the tool. The second would only work if we can come up with a way that works for every kind of color blindness (not sure if that's possible though).

Do you know if there is a standardized way in which a browser can tell the server that the user prefers a color blind color scheme? If so, I could use that to do serve the correct mode automatically.

Let me know what you think!

**Comment by francescor** [comment]
yes, 1. would solve, but asking a colorblind to choose colors is hard... maybe some 2/3 already made combinations one can just tick as you say in 2.

2. good too, easier to implement, too

I guess that for, "retro compatibility" kind of, you cannot change colors you use now, but if you can just choosing different level of darkness would fix:  light green, dark red

also repleacing the important color by adding stripes will just work 

![image](https://github.com/user-attachments/assets/66906add-e383-47d8-a9f7-1abfa802b006)


or even both 


![image](https://github.com/user-attachments/assets/dce4b1ae-1801-40eb-ad73-a3ed3733bc41)

well, then repleacing full color quares with 

![image](https://github.com/user-attachments/assets/ea822446-43f9-425c-8d8e-fe7b58f242fb)


would work too, but will look very bad, I know, while not  it looks neat :)


uh, I see this summarize everything https://www.perplexity.ai/search/i-have-an-app-that-shows-statu-dwTDyayxSEq3PUinagTjQA  but I checked the suggested "accessible colorblind color combinations" and cannot really get anything :(

**Comment by L7R7** [comment]
Alright, let me try a few ideas and come back to you when I have something to show.

**Comment by L7R7** [comment]
@francescor would the following work? ![image](https://github.com/user-attachments/assets/cfc77705-00fc-458e-8c49-350d847add59)

This uses different background patterns for all the different colors and it includes a textual representation of the status. This should work for all kinds of color blindness I'm aware of. The idea would be that there's a way to switch to a "colorblind mode" to activate that, by default it would use the color schema like before.

**Comment by francescor** [comment]
oh, great! even a blind man can see it ahhaha :) 

but yes, has to be an option, or else users will hate me for this request!

but, wait, there is no way to differentiate between good vs bad (apart then reading the content)

It would be better some kind of pattern that gives an idea that the failed is worst then cancelled, and successful is good

**Comment by L7R7** [comment]
> It would be better some kind of pattern that gives an idea that the failed is worst then cancelled, and successful is good

Agreed, I would definitely prefer a solution that does that over my idea mentioned above. I think what could work is a background that consists of a grid of "+" signs to indicate something positive, "-" for negative and "o" for something in between 

> oh, great! even a blind man can see it

side note: I do actually know a user of that tool who's legally blind, so improved screen reader support is on my list of improvements as well :smile:

**Comment by L7R7** [comment]
@francescor I know it's been a while since you last heard from me here, unfortunately I wasn't able to find much time for open source work over the last weeks. Thank you for your patience!

To illustrate my idea, this is what I had in mind: 

<img src="https://github.com/user-attachments/assets/bc1f1b8c-c4cb-44e6-80b3-e45c70a112de" width="50%">

That's a screenshot of a single tile. It shows a successful pipeline, so the backgrounds are green checkmarks. In addition to that, there's a textual representation of the status below the project name.

Do you think that'll work? If so, I'll try to adapt that for the other cases and see how I can provide it non-breaking as a new "accessibility mode" or something.

**Comment by francescor** [comment]
@L7R7 this would be SUPER!

really smart!

**Comment by L7R7** [comment]
@francescor I just published the first version of an accessibility mode that should improve the experience for colorblind users. The latest docker image contains that, it can be accessed via a link on the page itself or by appending `ui=no-color` as a URL parameter. It's not finished, but I wanted to finally provide you with something to try out and then iterate from there based on your feedback.

Let me know how well that works for you, I'm looking forward to your feedback! (and please, don't hurry. I hope you're currently having some days off to enjoy the christmas break. This can wait until January).

**Comment by francescor** [comment]
lovely! 
We'll deploy it in production right away!

**Comment by francescor** [comment]
@L7R7 the output is still the same, but I see we are pulling still old code (latest version is still the same)

We are using

```
  pipeline-monitor:
    image: l7r7/gitlab-ci-build-statuses:latest
```

should I change it?

**Comment by L7R7** [comment]
@francescor that's probably because something is caching the image and doesn't pull it everytime. To fix that, you could pin the version to a specific image hash. We're doing that in our deployments, the image name for the latest version is `l7r7/gitlab-ci-build-statuses:latest@sha256:ef3050774e0cf46db0c64f8e22330735dc76fe9c9ad3b231fedcce4f75c2ea09` We're using Kubernetes, but I think that should work on other platforms as well

**Comment by francescor** [comment]
yes, super, you are right.
I confirm it works!

we can tell the difference, very good, but now that I see a lot of blocks I like better your previous https://github.com/L7R7/gitlab-ci-build-statuses/issues/185#issuecomment-2383357612

**Comment by L7R7** [comment]
thank you for your feedback, glad to see that the new mode is a step in the right direction.
I'd prefer not to switch to the variant with the different backgorund textures, because as you said previously, there's no way to immediately see whether a pipeline is healthy or not. The checkmarks and crosses do that. Let's see if we can iterate on that to improve your experience.

One of the known issues is that the background pattern is not always ideal, that's probably something to be fixed with CSS (I'll talk to a colleague of mine who knows more CSS than me, I'm sure we'll find a solution then). So, for example, this is defintiely not what I intended: 
![image](https://github.com/user-attachments/assets/8b452a85-b864-49d2-9dbe-01a21cdc735a)
Instead, it should look more like this:
![image](https://github.com/user-attachments/assets/7c04ceb5-396c-4f65-9aa9-038d6557148b)
The size of the different tiles depends on the number of tiles that's shown, very few tiles lead to the overlap shown in the first screenshot.

Independently from that, I'll experiment with smaller icons in the background to see if that feels better.

**Comment by L7R7** [comment]
Can you maybe share some numbers on your usage? Especially, how many projects are shown on the page? Roughly, how many of them are usually healthy/broken/running?

**Comment by L7R7** [comment]
alright, two suggestions:
more, smaller icons:
![image](https://github.com/user-attachments/assets/8a7daec3-149b-42b9-98c6-a60250df84ec)

no border around the different tiles:
![image](https://github.com/user-attachments/assets/26f6a6ea-82a4-47db-a212-e2046a1d4b22)

**Comment by francescor** [comment]
Hi, 
we have about 20 lines, each with 7 squares, splitted in about 6 group of projects

**Comment by francescor** [comment]
what about leaving the full green background only for the "successfull" and use the new pattern for failed/warning ?

**Comment by L7R7** [comment]
This is another iteration: 
![image](https://github.com/user-attachments/assets/c86ec8c7-35e7-47e1-96ba-d8a18763df39)

From my side, this could be deployed now, but I'll still want to incorporate your feedback, @francescor :

> we have about 20 lines, each with 7 squares, splitted in about 6 group of projects

That's a little more than what we have at work, thank you! I'll reconstruct that locally to see how that feels.

> what about leaving the full green background only for the "successfull" and use the new pattern for failed/warning ?

That's also an interesting idea, maybe it's worth trying a version that uses the same background colors as the default mode and only adds the icons in black on top? What I'm trying to achieve is that the icons closely match the color scheme so that users with color blindness have the same information.

One thing I just remembered: There is a button at the bottom to hide successful pipelines. I added this with screen reader users in mind, maybe that helps you as well? In scenarios with a lot of projects and a large portion of successful pipelines that should bring more clarity

**Comment by francescor** [comment]
> This is another iteration

very, very good!

> maybe it's worth trying a version that uses the same background colors as the default mode and only adds the icons in black on top? 

mah, I think your last "iteration" looks great: if I pull the latest will I see it? 

> One thing I just remembered: There is a button at the bottom to hide successful pipelines

uh, bravo, that will be used for sure

**Comment by L7R7** [comment]
@francescor I just merged the PR, the new docker image is available, you can pull it now

**Comment by francescor** [comment]
I confirm everything works great:  on more colleague, with problem with color, too, is pretty happy, thanks!

(they also like the "hide successful")
